spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wx0381d394124496f2
  mpAppSecret: 1ca798a76360d378be53ebd907885fa2
  pay:
    mpAppId: wxd898fcb01713c658
    mchId: 1483469312
    mchKey: C5245D70627C1F8E9964D494B0735025
    keyPath: /Users/dealsky/path/h5.p12
    notifyUrl: http://dealsky.s1.natapp.cc/sell/pay/notify